apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deploy
  namespace: nginx
  labels:
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata: 
      labels:
        type: frontend
    spec:
      containers:
      - name: static-frontend
        image: ospf2fullstack/local:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: static-services
  namespace: nginx
  labels:
    type: frontend
spec:
  selector:
    type: frontend
  type: NodePort
  ports:
  - name: http
    port: 8080 # cluster port
    targetPort: 80 # pod port
    nodePort: 30001 # external node port
